In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [3]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5]) #creating numpy array
print(arr)
type(arr) #checking type of array

[1 2 3 4 5]


numpy.ndarray

In [5]:
#0-D array
a = np.array(42)
print(a)
print(type(a))
print(a.ndim)

#1-D array
b = np.array([1, 2, 3, 4, 5])
print(b)
print(type(b))
print(b.ndim)

#2D array
c = np.array([[1, 2, 3], [4, 5,6]])
print(c)
print(type(c))
print(c.ndim)

#3-D array
d = np.array([[[1, 2, 3], [4, 5,6]],[[1, 2, 3], [4, 5,6]]])
print(d)
print(type(d))
print(d.ndim)


42
<class 'numpy.ndarray'>
0
[1 2 3 4 5]
<class 'numpy.ndarray'>
1
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
3


# Array Shape and reshape

In [6]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape) #shape ?? kitne rows and columns hain

(2, 4)


In [7]:
#reshaping of nd array. Changing shape of array. add remove or change no. of elements in each dimension
#converting 1D to 2D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4,3)
print(newarr)
#elements required in each shape should be same

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
#Flattening array - converting multidimensional array to 1D array.
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [9]:
#indexing
arr = np.array([1,2,3,4])
print(arr[3])

4


In [10]:
arr = np.array([1,2,3,4])
print(arr[2]+arr[3]) #direct addition

7


In [11]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0,1]) # (row,column)


2nd element on 1st row:  2


In [12]:
a = np.array([3,4,5,6])

In [13]:
a

array([3, 4, 5, 6])

In [14]:
a.ndim

1

In [15]:
a[0], a[2]

(3, 5)

In [16]:
#2D array
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [17]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
#access element from 2nd row and 5th column
b[1,4]

10

# array iteration


In [19]:
arr = np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [21]:
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [24]:
#accessing individual elements of a  2D array
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x: #nested for loop
        print(y)

1
2
3
4
5
6


## slicing

In [31]:
arr = np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [32]:
print(arr[1:5]) # start index is included in the answer
# end index is not included in the answer

[2 3 4 5]


In [33]:
print(arr[2:])

[3 4 5 6 7]


In [34]:
print(arr[:5])

[1 2 3 4 5]


In [35]:
print(arr[1:5:2])

[2 4]


In [36]:
#slicing 2D array
                #index = 0    index =1
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4]) # [index of array, slicing]

[7 8 9]


In [37]:
arr[0,0:3]

array([1, 2, 3])

# searching and sorting

In [38]:
arr = np.array([1,2,3,4,5,4,4])

In [39]:
x = np.where(arr == 4) #return array of index position k 4 kahan pe hai
print(x)

(array([3, 5, 6], dtype=int64),)


In [40]:
#find indexes where values are even
arr = np.array([1,2,3,4,5,6,7,8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [42]:
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [43]:
arr = np.array(['banana','cherry','apple'])
print(np.sort(arr)) #sort acc to forst alphabet

['apple' 'banana' 'cherry']
