In [6]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [3]:
import numpy as np

In [7]:
arr = np.array([1, 2, 3, 4, 5]) #creating numpy array
print(arr)
type(arr) #checking type of array

[1 2 3 4 5]


numpy.ndarray

In [15]:
#0-D array
a = np.array(42)
print(a)
print(type(a))
print(a.ndim)

#1-D array
b = np.array([1, 2, 3, 4, 5])
print(b)
print(type(b))
print(b.ndim)

#2D array
c = np.array([[1, 2, 3], [4, 5,6]])
print(c)
print(type(c))
print(c.ndim)

#3-D array
d = np.array([[[1, 2, 3], [4, 5,6]],[[1, 2, 3], [4, 5,6]]])
print(d)
print(type(d))
print(d.ndim)


42
<class 'numpy.ndarray'>
0
[1 2 3 4 5]
<class 'numpy.ndarray'>
1
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
3


# Array Shape and reshape

In [16]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape) #shape ?? kitne rows and columns hain

(2, 4)


In [22]:
#reshaping of nd array. Changing shape of array. add remove or change no. of elements in each dimension
#converting 1D to 2D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4,3)
print(newarr)
#elements required in each shape should be same

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
#Flattening array - converting multidimensional array to 1D array.
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [26]:
#indexing
arr = np.array([1,2,3,4])
print(arr[3])

4


In [27]:
arr = np.array([1,2,3,4])
print(arr[2]+arr[3]) #direct addition

7


In [28]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0,1]) # (row,column)


2nd element on 1st row:  2


In [29]:
a = np.array([3,4,5,6])

In [30]:
a

array([3, 4, 5, 6])

In [31]:
a.ndim

1

In [33]:
a[0], a[2]

(3, 5)

In [36]:
#2D array
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [38]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
#access element from 2nd row and 5th column
b[1,4]

10